name: admin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  flutter_map_cancellable_tile_provider: ^3.0.0-dev.1
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  lottie: ^3.1.0
  permission_handler: ^11.3.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.9
  file_picker: ^5.2.0
  #flutter_map: ^3.1.0
  #latlong2: ^0.8.1
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  assets:
    - assets/copy.jpg
    - assets/appbar.png
    - assets/Flow.json
    - assets/images/jjm.png
    - assets/images/iitk.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/background.png

  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
